### PR TITLE
Reload slaves using USR2 process control signal

### PR DESCRIPTION
**Pull request by AntonTyutin**

### CODE REVIEW

**Comment by fiskWasTaken** [comment]
I was about to ask if you sent this PR to the right fork (this isn't the official one) but... I guess you're using this one? I'm still waiting for the PRs on this repo to be merged.

**Comment by fiskWasTaken** [comment]
I'll merge it anyway and cherry-pick this change into my reload PR.

Edit: disregard, you chose the right branch. Github mobile omits too much information...

**Comment by AntonTyutin** [comment]
I've made PR to this branch of your fork meaningly. I think my little addition should be a part of your solution within general PR. )

**Comment by fiskWasTaken** [comment]
Yes, understood. Thankyou.

**Pull request merged**
